/** DOWNLOAD REGISTRATION RECEIPT — the receipt is generated by the server from database data. */
import { applicantApi } from '../api/services.js';
import { downloadText } from '../ui/format.js';
import { setLoading } from '../ui/form.js';
import { toast } from '../ui/toast.js';

export async function downloadReceipt(btn, registrationNumber) {
  const restore = btn ? setLoading(btn, 'GENERATING') : () => {};
  try {
    const html = await applicantApi.receipt();
    downloadText(`NEXUS-Receipt-${registrationNumber || 'application'}.html`, html);
    toast('Receipt downloaded. Open it and use Print → Save as PDF if you need a PDF.', 'success', 6000);
  } catch (err) {
    toast(err.message, 'error');
  } finally {
    restore();
  }
}
